services:
  frontend:
    container_name: todoList-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true

  test:
    container_name: todoList-test
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CI=true
    command: npm test
